[package]
name = "local_oracle"
type = "contract"
authors = ["wonderland"]
compiler_version = ">=0.23.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.26.0", directory="noir-projects/aztec-nr/aztec" }